"""Fail on residue in active CSM files."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
BASELINE_PATH = DEFAULT_ROOT / "scripts" / "hygiene_known_findings.txt"

SCAN_ROOTS = (
    "README.md",
    ".github",
    "docs",
    "src",
    "tests",
    "eval/*.py",
)

QUARANTINE_ALLOWLIST = (
)

IGNORED_PATHS = (
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "htmlcov",
)

IGNORED_SUFFIXES = (
    ".pyc",
    ".pyo",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".pdf",
    ".zip",
    ".gz",
    ".sqlite",
    ".db",
)

SOURCE_COMPANY_PATTERNS = (
    re.compile("".join(("tr", "uck", "pi", "pes")), re.IGNORECASE),
    re.compile("".join(("gr", "and", r"[ -]?", "ro", "ck")), re.IGNORECASE),
    re.compile("".join(("ra", "ney")), re.IGNORECASE),
    # Parent project, prior employer, and author PII — split so this file never
    # matches itself. The two-letter abbreviation is case-sensitive to skip words
    # like "program"/"grand".
    re.compile("".join((r"\bre", "ter", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bve", "lo3d", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bow", "en", r"\b")), re.IGNORECASE),
    re.compile("".join(("osch", "oeniger")), re.IGNORECASE),
    re.compile("".join((r"\bG", r"R\b"))),
)

WRONG_DOMAIN_PATTERNS = (
    re.compile("".join((r"\bfulfill", "ment", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bship", "_date", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bpart", "_numbers", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\binventory", r"\.json\b")), re.IGNORECASE),
    re.compile("".join((r"\bs", "ku", r"\b")), re.IGNORECASE),
)

META_RESIDUE_PATTERNS = (
    re.compile("".join((r"\bload", r"[- ]?", "bearing", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bload", "bearing", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bCo", "dex", r"\b"))),
    re.compile("".join((r"\bChat", "GPT", r"\b"))),
    re.compile("".join((r"\bAI", "-generated", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bgenerated by ", "AI", r"\b")), re.IGNORECASE),
    re.compile(r"\bportfolio\b", re.IGNORECASE),
    re.compile(r"\bhiring\b", re.IGNORECASE),
    re.compile(r"\bJD\b"),
    re.compile(r"\bjob description\b", re.IGNORECASE),
    re.compile(r"\brole-relevant\b", re.IGNORECASE),
    re.compile(r"\bproof-of-craft\b", re.IGNORECASE),
    re.compile(r"\bapply for the\b", re.IGNORECASE),
    re.compile(r"\bresume bullet\b", re.IGNORECASE),
    re.compile(r"\bkiller scenario\b", re.IGNORECASE),
    re.compile(r"\bdo this next\b", re.IGNORECASE),
    re.compile(r"\bthe trap\b", re.IGNORECASE),
    re.compile(r"\bvibes\b", re.IGNORECASE),
)


@dataclass(frozen=True)
class Finding:
    path: Path
    line_no: int
    kind: str
    match: str
    line_hash: str

    def baseline_key(self, root: Path = DEFAULT_ROOT) -> str:
        rel = self.path.relative_to(root).as_posix()
        raw = f"{rel}:{self.line_no}:{self.kind}:{self.line_hash}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def iter_files(paths: tuple[str, ...], *, root: Path = DEFAULT_ROOT) -> list[Path]:
    files: list[Path] = []
    for raw in paths:
        if any(ch in raw for ch in "*?[]"):
            files.extend(p for p in root.glob(raw) if p.is_file())
            continue
        path = root / raw
        if path.is_dir():
            files.extend(p for p in path.rglob("*") if p.is_file())
        elif path.is_file():
            files.append(path)
    return sorted(files)


def _rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _is_ignored(path: Path, root: Path) -> bool:
    rel = _rel(path, root)
    parts = set(Path(rel).parts)
    return (
        bool(parts & set(IGNORED_PATHS))
        or path.suffix.lower() in IGNORED_SUFFIXES
        or rel.endswith(".egg-info/PKG-INFO")
    )


def _is_allowed(path: Path, root: Path) -> bool:
    rel = _rel(path, root)
    return any(
        rel == allowed or rel.startswith(f"{allowed}/")
        for allowed in QUARANTINE_ALLOWLIST
    )


def _raw_scan(
    paths: tuple[str, ...] = SCAN_ROOTS,
    *,
    root: Path = DEFAULT_ROOT,
) -> list[Finding]:
    findings: list[Finding] = []
    for path in iter_files(paths, root=root):
        if _is_ignored(path, root) or _is_allowed(path, root):
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for line_no, line in enumerate(text.splitlines(), start=1):
            line_hash = hashlib.sha256(line.encode("utf-8")).hexdigest()[:16]
            for pattern in SOURCE_COMPANY_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "source-residue", match.group(0), line_hash)
                    )
            for pattern in WRONG_DOMAIN_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "wrong-domain", match.group(0), line_hash)
                    )
            for pattern in META_RESIDUE_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "meta-residue", match.group(0), line_hash)
                    )
    return findings


def load_baseline(path: Path = BASELINE_PATH) -> set[str]:
    if not path.exists():
        return set()
    return {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def scan(
    paths: tuple[str, ...] = SCAN_ROOTS,
    *,
    root: Path = DEFAULT_ROOT,
    use_baseline: bool = True,
) -> list[Finding]:
    findings = _raw_scan(paths, root=root)
    if not use_baseline or root != DEFAULT_ROOT:
        return findings
    baseline = load_baseline()
    return [finding for finding in findings if finding.baseline_key(root) not in baseline]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", help="Optional repo-relative paths to scan")
    parser.add_argument(
        "--refresh-baseline",
        action="store_true",
        help="Write the current broad scan findings as the known inherited baseline",
    )
    args = parser.parse_args(argv)
    paths = tuple(args.paths) if args.paths else SCAN_ROOTS
    if args.refresh_baseline:
        findings = _raw_scan(SCAN_ROOTS)
        keys = sorted({finding.baseline_key() for finding in findings})
        BASELINE_PATH.write_text(
            "# Known inherited hygiene finding fingerprints. Do not add to this file for new CSM code.\n"
            + "\n".join(keys)
            + ("\n" if keys else ""),
            encoding="utf-8",
        )
        print(f"wrote {BASELINE_PATH.relative_to(DEFAULT_ROOT)} ({len(keys)} findings)")
        return 0
    findings = scan(paths)
    for finding in findings:
        rel = finding.path.relative_to(DEFAULT_ROOT)
        print(f"{rel}:{finding.line_no}: {finding.kind}: {finding.match}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
