"""Fail on residue in active CSM files."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
BASELINE_PATH = DEFAULT_ROOT / "scripts" / "hygiene_known_findings.txt"

SCAN_ROOTS = (
    "README.md",
    ".github",
    "docs",
    "src",
    "tests",
    "eval/*.py",
)

QUARANTINE_ALLOWLIST = (
)

IGNORED_PATHS = (
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "htmlcov",
)

IGNORED_SUFFIXES = (
    ".pyc",
    ".pyo",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".pdf",
    ".zip",
    ".gz",
    ".sqlite",
    ".db",
)

SOURCE_COMPANY_PATTERNS: tuple[re.Pattern[str], ...] = ()

WRONG_DOMAIN_PATTERNS = (
    re.compile("".join((r"\bfulfill", "ment", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bship", "_date", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bpart", "_numbers", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\binventory", r"\.json\b")), re.IGNORECASE),
    re.compile("".join((r"\bs", "ku", r"\b")), re.IGNORECASE),
)

# MP-W1R (D7): a normalized-token DIGEST denylist, distinct from
# SOURCE_COMPANY_PATTERNS above. That regex list splits terms across string
# concatenation so this file doesn't self-match, but the term is still
# reconstructable by anyone reading this source (concatenate the parts).
# A digest cannot be reversed -- this list is enforceable by an executor who
# never learns the underlying term, per the PRD rule (private reference
# dataset: patterns as priors only, name never in any artifact). Digests
# ONLY below -- no comment, variable name, or fixture may spell the term.
DIGEST_DENYLIST: tuple[str, ...] = (
    "f9366fbcf2c0e3980ada3808a3fa1965ab8cfdf3c36224b5ba95a62a7d65a257",
    "4e0c381ece8a5bfbe50226bc3a3b65ebd4a755ff6eb2b7a79a2e7d4bcf9850d4",
    "9edf28f224d98f07ee572d8ac1dbe88d4177f48387c47ca107f18d55581baadd",
    "c84fe3a544b2482b4858aba7379fb88822889b4dce8585c1e801e0a6bc18e52c",
    "8f7cecc6ba67e7cf74ef6b9eef3cc333d15d6b582acbb43a13223f6b12a38144",
    "b8746e3fc5eb4f3db7a73acbcb68c250d73d998ac6a12933365aff9bcb53028d",
    "3269fcdae666f0aaa3b320d07a7d9351c46e5a5e8f6ac07f2fc77770eb0055ef",
    "2b3dac6c72b05a6ed28f85b58b2d960a8863a7e7871e94f7316fc0d7ec86e9a6",
    "2b219c9dc0a7a2a959547cd5feef227367df511bf80acb2bd07263ac98b4eb9d",
    "0e6a8e0b849ed9b064c5a25e1ee5592f427e3eb9d250e42069ce46147d00e8d4",
    "b67edcdb95503aaeb8980b7017c4f7488871ce5908a5c945fb1b6334b808e960",
    "ad3e69e9aa860657cc6476770fe253d08198746b9fcf9dc3186b47eb85c30335",
    "e02a2f606a57969379293b790c2e1af0a24146c7b26430552a4381e31b74147c",
    "2e91a54572f85c89684bbe8f642aa1797da01e1c16d7fc285efea9ae41247ee9",
    "0673326b7dd1623e319e92d365939e1e9efaf5b91e68828db8e56ce487d364e2",
    "a3a6bcc0c7a37cf8d7660f9facf18f8dd3beee6a1b3dac664d1392202c467db0",
    "8a060641f3086e3d746264cb8abf3582ebf464ee1f17524d3c80d72095620c14",
    "7b222a9a25911d8213251821ae8c210a14db05604c778cb26c980d36196b763a",
)
SINGLE_TOKEN_DIGEST_DENYLIST: tuple[str, ...] = (
    "183ee0870433a102edb987ee4924a9d4f39af24db56c0e5d01bb9e8e56263439",
)

_TOKEN_RE = re.compile(r"[a-z0-9]+")


def _normalized_tokens(line: str) -> list[str]:
    return _TOKEN_RE.findall(line.lower())


def _digest_hit_count(line: str, denylist: tuple[str, ...] = DIGEST_DENYLIST) -> int:
    """Hash every single token AND every adjacent-pair join, compare
    against the denylist. Pair-joining catches a two-word term split across
    normal word boundaries (the case this exists for); single tokens catch
    it written as one word. Returns a COUNT only, deliberately -- returning
    the matched candidate string would print the very term this exists to
    keep out of every artifact, defeating the whole mechanism the moment a
    real hit occurs."""
    if not denylist and not SINGLE_TOKEN_DIGEST_DENYLIST:
        return 0
    denylist_set = set(denylist)
    tokens = _normalized_tokens(line)
    candidates = [a + b for a, b in zip(tokens, tokens[1:])]
    joined_hits = sum(
        1
        for candidate in candidates
        if hashlib.sha256(candidate.encode("utf-8")).hexdigest() in denylist_set
    )
    single_denylist = denylist_set | set(SINGLE_TOKEN_DIGEST_DENYLIST)
    single_hits = sum(
        1
        for token in tokens
        if hashlib.sha256(token.encode("utf-8")).hexdigest() in single_denylist
    )
    return joined_hits + single_hits


META_RESIDUE_PATTERNS = (
    re.compile("".join((r"\bload", r"[- ]?", "bearing", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bload", "bearing", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bCo", "dex", r"\b"))),
    re.compile("".join((r"\bChat", "GPT", r"\b"))),
    re.compile("".join((r"\bAI", "-generated", r"\b")), re.IGNORECASE),
    re.compile("".join((r"\bgenerated by ", "AI", r"\b")), re.IGNORECASE),
    re.compile(r"\bkiller scenario\b", re.IGNORECASE),
    re.compile(r"\bdo this next\b", re.IGNORECASE),
    re.compile(r"\bthe trap\b", re.IGNORECASE),
    re.compile(r"\bvibes\b", re.IGNORECASE),
)


@dataclass(frozen=True)
class Finding:
    path: Path
    line_no: int
    kind: str
    match: str
    line_hash: str

    def baseline_key(self, root: Path = DEFAULT_ROOT) -> str:
        rel = self.path.relative_to(root).as_posix()
        raw = f"{rel}:{self.line_no}:{self.kind}:{self.line_hash}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def iter_files(paths: tuple[str, ...], *, root: Path = DEFAULT_ROOT) -> list[Path]:
    files: list[Path] = []
    for raw in paths:
        if any(ch in raw for ch in "*?[]"):
            files.extend(p for p in root.glob(raw) if p.is_file())
            continue
        path = root / raw
        if path.is_dir():
            files.extend(p for p in path.rglob("*") if p.is_file())
        elif path.is_file():
            files.append(path)
    return sorted(files)


def _rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _is_ignored(path: Path, root: Path) -> bool:
    rel = _rel(path, root)
    parts = set(Path(rel).parts)
    return (
        bool(parts & set(IGNORED_PATHS))
        or path.suffix.lower() in IGNORED_SUFFIXES
        or rel.endswith(".egg-info/PKG-INFO")
    )


def _is_allowed(path: Path, root: Path) -> bool:
    rel = _rel(path, root)
    return any(
        rel == allowed or rel.startswith(f"{allowed}/")
        for allowed in QUARANTINE_ALLOWLIST
    )


def _raw_scan(
    paths: tuple[str, ...] = SCAN_ROOTS,
    *,
    root: Path = DEFAULT_ROOT,
) -> list[Finding]:
    findings: list[Finding] = []
    for path in iter_files(paths, root=root):
        if _is_ignored(path, root) or _is_allowed(path, root):
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for line_no, line in enumerate(text.splitlines(), start=1):
            line_hash = hashlib.sha256(line.encode("utf-8")).hexdigest()[:16]
            for pattern in SOURCE_COMPANY_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "source-residue", match.group(0), line_hash)
                    )
            for pattern in WRONG_DOMAIN_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "wrong-domain", match.group(0), line_hash)
                    )
            for pattern in META_RESIDUE_PATTERNS:
                match = pattern.search(line)
                if match:
                    findings.append(
                        Finding(path, line_no, "meta-residue", match.group(0), line_hash)
                    )
            for _ in range(_digest_hit_count(line, DIGEST_DENYLIST)):
                # DIGEST_DENYLIST re-read from module globals here (not a
                # bound default) so a test can monkeypatch the module-level
                # name and have it actually take effect at call time.
                # match is deliberately a fixed redaction, never the actual
                # matched text -- see _digest_hit_count's docstring.
                findings.append(Finding(path, line_no, "digest-residue", "[redacted]", line_hash))
    return findings


def load_baseline(path: Path = BASELINE_PATH) -> set[str]:
    if not path.exists():
        return set()
    return {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def scan(
    paths: tuple[str, ...] = SCAN_ROOTS,
    *,
    root: Path = DEFAULT_ROOT,
    use_baseline: bool = True,
) -> list[Finding]:
    findings = _raw_scan(paths, root=root)
    if not use_baseline or root != DEFAULT_ROOT:
        return findings
    baseline = load_baseline()
    return [finding for finding in findings if finding.baseline_key(root) not in baseline]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", help="Optional repo-relative paths to scan")
    parser.add_argument(
        "--refresh-baseline",
        action="store_true",
        help="Write the current broad scan findings as the known inherited baseline",
    )
    args = parser.parse_args(argv)
    paths = tuple(args.paths) if args.paths else SCAN_ROOTS
    if args.refresh_baseline:
        findings = _raw_scan(SCAN_ROOTS)
        keys = sorted({finding.baseline_key() for finding in findings})
        BASELINE_PATH.write_text(
            "# Known inherited hygiene finding fingerprints. Do not add to this file for new CSM code.\n"
            + "\n".join(keys)
            + ("\n" if keys else ""),
            encoding="utf-8",
        )
        print(f"wrote {BASELINE_PATH.relative_to(DEFAULT_ROOT)} ({len(keys)} findings)")
        return 0
    findings = scan(paths)
    for finding in findings:
        rel = finding.path.relative_to(DEFAULT_ROOT)
        print(f"{rel}:{finding.line_no}: {finding.kind}: {finding.match}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
