"""Render STATUS.md from local artifact files."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = ROOT / "STATUS.md"

ARTIFACTS = {
    "scorecard": Path("eval/scorecard_csm.json"),
    "regression": Path("eval/regression_csm.json"),
    "quality_regression": Path("eval/quality_regression_csm.json"),
    "judge_agreement": Path("eval/gold/judge_agreement.json"),
    "demo_loop": Path("eval/demo_loop_csm.json"),
    "deep_vs_shallow": Path("eval/deep_vs_shallow_detection.json"),
}

READINESS_ARTIFACTS = (
    Path("eval/source_readiness.json"),
    Path("demo_state/source_readiness.json"),
)


@dataclass(frozen=True)
class JsonArtifact:
    name: str
    rel_path: Path
    payload: dict[str, Any] | None
    error: str | None = None

    @property
    def state(self) -> str:
        if self.payload is not None:
            return "loaded"
        return self.error or "missing"


def render_status(root: Path = ROOT) -> str:
    artifacts = {
        name: _load_json(root, name, rel_path)
        for name, rel_path in ARTIFACTS.items()
    }
    readiness = _load_first_readiness(root)
    lines: list[str] = [
        "# Ultra CSM Status",
        "",
        "_Generated by `scripts/render_status.py` from local artifacts. Do not edit by hand._",
        "",
        "## Artifact Inputs",
        "",
        "| Artifact | Path | State |",
        "|---|---|---|",
    ]
    for artifact in (*artifacts.values(), readiness):
        lines.append(f"| {artifact.name} | `{artifact.rel_path.as_posix()}` | {artifact.state} |")

    lines.extend(_scorecard_lines(artifacts["scorecard"]))
    lines.extend(_regression_lines(artifacts["regression"]))
    lines.extend(_quality_regression_lines(artifacts["quality_regression"]))
    lines.extend(_judge_agreement_lines(artifacts["judge_agreement"]))
    lines.extend(_readiness_lines(readiness))
    lines.extend(_demo_loop_lines(artifacts["demo_loop"]))
    lines.extend(_claim_boundary_lines(artifacts["deep_vs_shallow"]))
    lines.extend(_operating_proof_lines(root))
    return "\n".join(lines).rstrip() + "\n"


def write_status(root: Path = ROOT, path: Path | None = None) -> Path:
    target = path or root / "STATUS.md"
    target.write_text(render_status(root), encoding="utf-8")
    return target


def _load_json(root: Path, name: str, rel_path: Path) -> JsonArtifact:
    path = root / rel_path
    if not path.exists():
        return JsonArtifact(name=name, rel_path=rel_path, payload=None, error="missing")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return JsonArtifact(
            name=name,
            rel_path=rel_path,
            payload=None,
            error=f"invalid JSON: {exc.__class__.__name__}",
        )
    if not isinstance(payload, dict):
        return JsonArtifact(name=name, rel_path=rel_path, payload=None, error="not a JSON object")
    return JsonArtifact(name=name, rel_path=rel_path, payload=payload)


def _load_first_readiness(root: Path) -> JsonArtifact:
    for rel_path in READINESS_ARTIFACTS:
        artifact = _load_json(root, "source_readiness", rel_path)
        if artifact.payload is not None:
            return artifact
    return JsonArtifact(
        name="source_readiness",
        rel_path=READINESS_ARTIFACTS[0],
        payload=None,
        error="missing",
    )


def _scorecard_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Scorecard", ""]
    if payload is None:
        return lines + ["- No scorecard artifact loaded."]
    score = _dict(payload.get("score"))
    unsafe = _dict(payload.get("unsafe_placeholder"))
    lines.append(
        "- Hard gate: "
        f"{_bool(payload.get('hard_ok'))}; score={_score(score)}; "
        f"hard_failures={len(_list(payload.get('hard_failures')))}"
    )
    lines.append(f"- Measurement scope: {_text(payload.get('measurement_scope'))}")
    lines.append(
        "- Unsafe placeholder: "
        f"passed={_bool(unsafe.get('passed'))}; "
        f"failed_hard_gates={len(_list(unsafe.get('failed_hard_gates')))}"
    )
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _regression_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Regression", ""]
    if payload is None:
        return lines + ["- No regression artifact loaded."]
    spine = _dict(payload.get("deterministic_spine"))
    live_lane = _dict(payload.get("live_lane"))
    lines.append(
        "- Deterministic spine: "
        f"passed={_bool(spine.get('passed'))}; "
        f"comparison={_text(spine.get('comparison'))}; "
        f"changes={len(_list(spine.get('changes')))}"
    )
    lines.append(
        "- Regression gate: "
        f"hard_ok={_bool(payload.get('hard_ok'))}; "
        f"score={_score(_dict(payload.get('scorecard_score')))}; "
        f"mode={_text(payload.get('mode'))}"
    )
    if live_lane:
        lines.append(
            "- Live lane: "
            f"status={_text(live_lane.get('status'))}; "
            f"target={_text(live_lane.get('target'))}; "
            f"non_determinism_claimed={_bool(live_lane.get('non_determinism_claimed'))}"
        )
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _quality_regression_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Quality Regression", ""]
    if payload is None:
        return lines + ["- No quality-regression artifact loaded."]
    normal = _dict(_dict(payload.get("normal")).get("overall"))
    normal_band = _dict(normal.get("pass_rate_band"))
    sensitivity = _dict(payload.get("sensitivity"))
    specificity = _dict(payload.get("specificity"))
    lines.append(
        "- Offline mechanics: "
        f"hard_ok={_bool(payload.get('hard_ok'))}; "
        f"mode={_text(payload.get('mode'))}; "
        f"normal={_band(normal_band)}"
    )
    lines.append(
        "- Sensitivity/specificity: "
        f"sensitivity_passed={_bool(sensitivity.get('passed'))}; "
        f"specificity_passed={_bool(specificity.get('passed'))}"
    )
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _judge_agreement_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Judge Agreement", ""]
    if payload is None:
        return lines + ["- No judge-agreement artifact loaded."]
    clean = _dict(payload.get("clean_layer"))
    hard = _dict(payload.get("hard_layer"))
    lines.append(
        "- Clean layer: "
        f"n={_text(clean.get('n'))}; "
        f"min_dimension_kappa={_text(clean.get('min_dimension_kappa'))}; "
        f"min_judge_scored_dimension_kappa={_text(clean.get('min_judge_scored_dimension_kappa'))}"
    )
    lines.append(
        "- Hard layer: "
        f"n={_text(hard.get('n'))}; "
        f"min_dimension_kappa={_text(hard.get('min_dimension_kappa'))}; "
        f"min_judge_scored_dimension_kappa={_text(hard.get('min_judge_scored_dimension_kappa'))}"
    )
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _readiness_lines(artifact: JsonArtifact) -> list[str]:
    lines = ["", "## Source Readiness", ""]
    payload = artifact.payload
    if payload is None:
        return lines + [
            "- No source-readiness artifact loaded. Live tenant readiness is not claimed.",
        ]
    sources = _dict(payload.get("sources"))
    degraded = _list(payload.get("degraded_rails"))
    actions = _list(payload.get("required_operator_actions"))
    if sources:
        rendered = ", ".join(f"{key}={value}" for key, value in sorted(sources.items()))
    else:
        rendered = "none"
    lines.append(f"- Sources: {rendered}")
    lines.append(f"- Degraded rails: {len(degraded)}")
    lines.append(f"- Required operator actions: {len(actions)}")
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _demo_loop_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Sim Loop", ""]
    if payload is None:
        return lines + ["- No demo-loop artifact loaded."]
    first = _dict(payload.get("first_sweep"))
    second = _dict(payload.get("second_sweep"))
    breaker = _dict(_dict(payload.get("quality_breaker")).get("red"))
    lines.append(
        "- Sweeps: "
        f"first_accounts={len(_list(first.get('swept_accounts')))}; "
        f"first_degraded={_text(first.get('degraded_items'))}; "
        f"second_degraded={_text(second.get('degraded_items'))}"
    )
    lines.append(
        "- Quality breaker: "
        f"triggered={_bool(breaker.get('triggered'))}; "
        f"state={_text(breaker.get('state'))}; "
        f"degraded_items={_text(breaker.get('degraded_items'))}"
    )
    lines.append(f"- Outcomes recorded: {len(_list(payload.get('outcomes')))}")
    lines.append(f"- Claim boundary: {_claim_summary(payload)}")
    return lines


def _claim_boundary_lines(artifact: JsonArtifact) -> list[str]:
    payload = artifact.payload
    lines = ["", "## Claim Boundary Gaps", ""]
    if payload is None:
        return lines + ["- `eval/deep_vs_shallow_detection.json` was not loaded."]
    if isinstance(payload.get("claim_boundary"), dict):
        return lines + ["- `eval/deep_vs_shallow_detection.json` has a claim boundary."]
    return lines + [
        "- `eval/deep_vs_shallow_detection.json` lacks `claim_boundary`; "
        "no rendered claim is made from it.",
    ]


def _operating_proof_lines(root: Path) -> list[str]:
    path = root / "docs/OPERATING_PROOF.md"
    lines = ["", "## Operating Proof", ""]
    if not path.exists():
        return lines + ["- `docs/OPERATING_PROOF.md` is missing."]
    text = path.read_text(encoding="utf-8")
    date = "unknown"
    for line in text.splitlines():
        if line.startswith("Date:"):
            date = line.removeprefix("Date:").strip().rstrip(".")
            break
    drift = "deep_vs_shallow_detection.json" in text and "lacks a `claim_boundary`" in text
    lines.append(f"- Proof note date: {date}")
    lines.append(f"- Mentions deep-vs-shallow claim-boundary drift: {_bool(drift)}")
    return lines


def _claim_summary(payload: dict[str, Any]) -> str:
    claim = payload.get("claim_boundary")
    if not isinstance(claim, dict):
        return "missing"
    if not claim:
        return "empty"
    return ", ".join(f"{key}={_text(value)}" for key, value in sorted(claim.items()))


def _score(payload: dict[str, Any]) -> str:
    return f"passed={_text(payload.get('passed'))} total={_text(payload.get('total'))}"


def _band(payload: dict[str, Any]) -> str:
    if not payload:
        return "missing"
    return (
        f"passed={_text(payload.get('passed'))} total={_text(payload.get('total'))} "
        f"point={_text(payload.get('point'))} "
        f"lower={_text(payload.get('lower'))} upper={_text(payload.get('upper'))}"
    )


def _dict(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _list(value: object) -> list[Any]:
    return value if isinstance(value, list) else []


def _bool(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return _text(value)


def _text(value: object) -> str:
    if value is None:
        return "missing"
    if isinstance(value, bool):
        return _bool(value)
    if isinstance(value, (int, float, str)):
        return str(value)
    return json.dumps(value, sort_keys=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if STATUS.md is stale")
    args = parser.parse_args(argv)
    rendered = render_status(ROOT)
    if args.check:
        if not STATUS_PATH.exists() or STATUS_PATH.read_text(encoding="utf-8") != rendered:
            print("STATUS.md is stale; run `python scripts/render_status.py`")
            return 1
        print("STATUS.md is current")
        return 0
    STATUS_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {STATUS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
