name: clean-docs

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-docs:
    uses: owieschon/clean-docs/.github/workflows/reusable-clean-docs.yml@b1c145eca55a61cd28749fc34e329c3cbda08fc8
    with:
      package-ref: b1c145eca55a61cd28749fc34e329c3cbda08fc8
